CREATE SEQUENCE seq_zona
    START  1
    INCREMENT  1;




CREATE TABLE zona(
    ID BIGINT DEFAULT NEXTVAL('seq_zona') PRIMARY KEY,
    CODIGO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    COEF_APROVEITAMENTO NUMERIC(5,2) NOT NULL,
    TAXA_OCUPACAO NUMERIC(5,2) NOT NULL,
    TAXA_PERMEABILIDADE NUMERIC(5,2) NOT NULL,
    GABARITO NUMERIC(5,2) NOT NULL,
    RECUO_LATERAL NUMERIC(5,2) NOT NULL,
    RECUO_FRONTAL NUMERIC(5,2) NOT NULL,
    RECUO_FUNDO NUMERIC(5,2) NOT NULL,
    LOTE_MINIMO NUMERIC(5,2) NOT NULL
    );


CREATE SEQUENCE seq_uso_permitido
    START  1
    INCREMENT  1;



CREATE TABLE uso_permitido(
    ID BIGINT DEFAULT NEXTVAL('seq_uso_permitido') PRIMARY KEY,
    DESCRICAO VARCHAR(80) NOT NULL,
    NIVEL_INCOMODIDADE VARCHAR(80)  NOT NULL,
    ZONA_ID BIGINT REFERENCES ZONA(ID)
    );